name: nexus
description: A cross-platform web browser with advanced Linux desktop support
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  linux_webview:
    path: ./linux_webview
  window_manager: ^0.3.9
  url_launcher: ^6.1.14
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
