name: nexus_browser
description: A modern web browser built with Flutter and Elixir
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  phoenix_socket: ^1.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.18
  drift: ^2.14.1
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
