name: nexus_browser_ui
description: Flutter UI for Nexus Browser

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.82.1
  ffi: ^2.1.0
  webview_flutter: ^4.2.4
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  flutter_rust_bridge_codegen: ^1.82.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
