name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['frontend', 'linux_webview']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
        
    - name: Install Linux dependencies
      if: matrix.package == 'linux_webview'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libwebkit2gtk-4.0-dev
        
    - name: Install dependencies
      working-directory: ${{ matrix.package }}
      run: flutter pub get
      
    - name: Verify formatting
      working-directory: ${{ matrix.package }}
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Analyze project source
      working-directory: ${{ matrix.package }}
      run: flutter analyze
      
    - name: Run tests
      working-directory: ${{ matrix.package }}
      run: flutter test --coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ${{ matrix.package }}/coverage/lcov.info
        flags: ${{ matrix.package }}

  linux-build:
    runs-on: ubuntu-latest
    needs: flutter
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
        
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libwebkit2gtk-4.0-dev
        
    - name: Build Linux app
      run: |
        flutter config --enable-linux-desktop
        flutter build linux
